export const GAME_TUNING = Object.freeze({
  ammunition: Object.freeze({
    normal: Object.freeze({
      id: 0,
      name: "普通球",
      costType: "free",
      projectileCount: 1,
      burstInterval: 0,
      launchSpeed: 15,
      gravityMultiplier: 1,
      visualScale: 1,
      mass: 1,
      angularDamping: 0.05,
      cooldownOverride: -1,
      appearanceHoldDuration: 0,
      coinPrice: 0,
    }),
  }),
  ball: Object.freeze({
    cooldown: 0,
    lifetime: 2,
    baseLaunchSpeed: 18,
    spawnDelay: 0,
    muzzleEffectDelay: 0,
    radius: 0.35,
    firstCollisionSpeed: 5,
    firstCollisionAngularMultiplier: 0.5,
    launchRandomAngularSpeed: 1,
    firstCollisionShockwaveImpulse: 1,
    farDistanceDampingEnabled: true,
    farDistanceDamping: 1,
    dampingDepth: 20,
    outOfBoundsDepth: 20,
    stationarySpeed: 40,
    stationaryDuration: 0.05,
    stationaryRemainingLifetime: 0.5,
  }),
  physics: Object.freeze({
    fixedStep: 0.01666667,
    maxFrameCompensation: 0.05,
    gravity: 25,
    maxBallSpeed: 400,
    fallHeight: -5,
    horizontalHalfBoundary: 30,
    depthHalfBoundary: 30,
    blocksStartSleeping: true,
    prewarmDuration: 0.1,
    // Unity PhysX source values. Rapier does not expose equivalent
    // position/velocity iteration controls, so these remain reference data.
    sourcePositionSolverIterations: 50,
    sourceVelocitySolverIterations: 12,
    sourceActivePositionIterations: 24,
    sourceActiveVelocityIterations: 6,
    sourceFragmentPositionIterations: 1,
    sourceFragmentVelocityIterations: 1,
  }),
  blocks: Object.freeze({
    catalogMassMultiplier: 0.75,
    solverTierPropagationImpulse: 8,
  }),
  movingPlatform: Object.freeze({
    maxSpeed: 3,
    startupEaseDuration: 0.4,
    pinUndisturbedObjects: true,
    releaseVelocityDifference: 1.5,
  }),
});
